%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/sophia/Documents/CHEME5440/CHEME-5440-7770-PS3-S21-main/Stoich_matrix.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 24-Mar-2021 21:24:38

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "B2:J9";

% Specify column names and types
opts.VariableNames = ["v1", "v2", "v3", "v4", "v5", "b1", "b2", "b3", "b4"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Stoichmatrix = readtable("/Users/sophia/Documents/CHEME5440/CHEME-5440-7770-PS3-S21-main/Stoich_matrix.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

writetable(Stoichmatrix, "Network.dat")